name: Second_workflow

on: push

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: echo "Hi this Anchal and here we are running GitHub Actions"

  Bye-job:
    runs-on: ubuntu-latest
    steps:
      - name: Bye Job
        run: echo "Nye Bye, aapka safar shubh ho"