name : Second_workflow ;
#this is name 
on : push
#what event is trigeering

jobs : 
       hello-job :
           runs-on : ubuntu-latest
           #on which ptalforn it runs
           steps : 
             - name : "welcome"
               run : echo "Hi this Anchal and here we are running github actions"

       Bye-job : 
       runs-on : ubuntu-latest
       steps :
         - name :  "Bye Job"
           run : echo " Nye Bye aapka safar shubh ho"
    